export const gameCalendarData = [
  {
    id: 1,
    typ: 'liga',
    data: '2024-02-13',
    nazwa_pierwszej_druzyny: 'Pierwsza',
    logo_pierwszej_druzyny: 'logo1.png',
    bramki_pierwszej_druzyny: '3',
    nazwa_drugiej_druzyny: 'Druga Drużyna 1',
    logo_drugiej_druzyny: 'logo2.png',
    bramki_drugiej_druzyny: '2',
  },
  {
    id: 2,
    typ: 'liga',
    data: '2024-02-14',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 2',
    logo_pierwszej_druzyny: 'logo3.png',
    bramki_pierwszej_druzyny: '1',
    nazwa_drugiej_druzyny: 'Druga Drużyna 2',
    logo_drugiej_druzyny: 'logo4.png',
    bramki_drugiej_druzyny: '1',
  },
  {
    id: 3,
    typ: 'sparing',
    data: '2024-02-15',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 3',
    logo_pierwszej_druzyny: 'logo5.png',
    bramki_pierwszej_druzyny: '2',
    nazwa_drugiej_druzyny: 'Druga Drużyna 3',
    logo_drugiej_druzyny: 'logo6.png',
    bramki_drugiej_druzyny: '4',
  },
  {
    id: 4,
    typ: 'liga',
    data: '2024-02-16',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 4',
    logo_pierwszej_druzyny: 'logo7.png',
    bramki_pierwszej_druzyny: '5',
    nazwa_drugiej_druzyny: 'Druga Drużyna 4',
    logo_drugiej_druzyny: 'logo8.png',
    bramki_drugiej_druzyny: '3',
  },
  {
    id: 5,
    typ: 'sparing',
    data: '2024-02-17',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 5',
    logo_pierwszej_druzyny: 'logo9.png',
    bramki_pierwszej_druzyny: '1',
    nazwa_drugiej_druzyny: 'Druga Drużyna 5',
    logo_drugiej_druzyny: 'logo10.png',
    bramki_drugiej_druzyny: '0',
  },
  {
    id: 6,
    typ: 'liga',
    data: '2024-02-18',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 6',
    logo_pierwszej_druzyny: 'logo11.png',
    bramki_pierwszej_druzyny: '0',
    nazwa_drugiej_druzyny: 'Druga Drużyna 6',
    logo_drugiej_druzyny: 'logo12.png',
    bramki_drugiej_druzyny: '2',
  },
  {
    id: 7,
    typ: 'sparing',
    data: '2024-02-19',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 7',
    logo_pierwszej_druzyny: 'logo13.png',
    bramki_pierwszej_druzyny: '4',
    nazwa_drugiej_druzyny: 'Druga Drużyna 7',
    logo_drugiej_druzyny: 'logo14.png',
    bramki_drugiej_druzyny: '1',
  },
  {
    id: 8,
    typ: 'liga',
    data: '2024-02-20',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 8',
    logo_pierwszej_druzyny: 'logo15.png',
    bramki_pierwszej_druzyny: '2',
    nazwa_drugiej_druzyny: 'Druga Drużyna 8',
    logo_drugiej_druzyny: 'logo16.png',
    bramki_drugiej_druzyny: '2',
  },
  {
    id: 9,
    typ: 'liga',
    data: '2024-02-21',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 9',
    logo_pierwszej_druzyny: 'logo17.png',
    bramki_pierwszej_druzyny: '3',
    nazwa_drugiej_druzyny: 'Druga Drużyna 9',
    logo_drugiej_druzyny: 'logo18.png',
    bramki_drugiej_druzyny: '3',
  },
  {
    id: 10,
    typ: 'sparing',
    data: '2024-02-22',
    nazwa_pierwszej_druzyny: 'Pierwsza Drużyna 10',
    logo_pierwszej_druzyny: 'logo19.png',
    bramki_pierwszej_druzyny: '2',
    nazwa_drugiej_druzyny: 'Druga Drużyna 10',
    logo_drugiej_druzyny: 'logo20.png',
    bramki_drugiej_druzyny: '1',
  },
];
