name: Deploy to Hosting

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
          NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}

      - name: Deploy to MyDevil
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY_P }}
          script: |
            # Przejdź do katalogu z kodem źródłowym
            cd ~/domains/hcwroclaw.com/hcwroclaw

            # Pobierz najnowsze zmiany
            git pull

            # Zainstaluj zależności
            npm ci

            # Dodaj te zmienne środowiskowe
            export NEXT_TELEMETRY_DISABLED=1
            export NODE_OPTIONS="--max_old_space_size=4096"

            # Zbuduj aplikację
            npm run build

            # Skopiuj potrzebne pliki do katalogu public_nodejs
            cp -r .next ~/domains/hcwd3v.hcwroclaw.com/public_nodejs/
            cp -r public ~/domains/hcwd3v.hcwroclaw.com/public_nodejs/
            cp -r node_modules ~/domains/hcwd3v.hcwroclaw.com/public_nodejs/
            cp package.json ~/domains/hcwd3v.hcwroclaw.com/public_nodejs/
            cp next.config.mjs ~/domains/hcwd3v.hcwroclaw.com/public_nodejs/

            # Zrestartuj aplikację
            devil www restart hcwd3v.hcwroclaw.com
